spring:
  cloud:
    gcp:
      core:
        enabled: ${GCP_PUB_SUB_ENABLED:false}
      pubsub:
        enabled: ${GCP_PUB_SUB_ENABLED:false}
      project-id: ${GCP_PROJECT_ID:""}
      credentials:
        location: file:${GCP_CREDENTIALS_FILE_LOCATION:""}

publisher-configuration-file: ${PUBLISHER_CONFIGURATION_FILE_LOCATION:""}
subscriber-configuration-file: ${SUBSCRIBER_CONFIGURATION_FILE_LOCATION:""}
subscriber-schedule-configuration-file: ${SUBSCRIBER_SCHEDULE_CONFIGURATION_FILE_LOCATION:""}

management:
  endpoints:
    web:
      exposure:
        include: "*"