spring:
  cloud:
    gcp:
      core:
        enabled: ${GCP_PUB_SUB_ENABLED:false}
      pubsub:
        enabled: ${GCP_PUB_SUB_ENABLED:false}
      project-id: ${GCP_PROJECT_ID:""}
      credentials:
        location: file:${GCP_CREDENTIALS_FILE_LOCATION:""}

  datasource:
    url: jdbc:mysql://${EVENT_ROUTER_DB_HOST}:${EVENT_ROUTER_DB_PORT}/${EVENT_ROUTER_DB_NAME}?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=True
    username: ${EVENT_ROUTER_DB_USERNAME}
    password: ${EVENT_ROUTER_DB_PASSWORD}
  jpa:
    generate-ddl: false
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  liquibase:
    change-log: classpath:liquibase.xml

publisher-configuration-file: ${PUBLISHER_CONFIGURATION_FILE_LOCATION}
subscriber-configuration-file: ${SUBSCRIBER_CONFIGURATION_FILE_LOCATION}
subscriber-schedule-configuration-file: ${SUBSCRIBER_SCHEDULE_CONFIGURATION_FILE_LOCATION}

bahmni:
  baseUrl: http://${OPENMRS_HOST}:${OPENMRS_PORT}
  authUrl: ${bahmni.baseUrl}/openmrs/ws/rest/v1/session
  user: ${OPENMRS_ATOMFEED_USER}
  password: ${OPENMRS_ATOMFEED_PASSWORD}
  connectionTimeoutInMilliseconds: ${CONNECTION_TIMEOUT_IN_MILLISECONDS}
  replyTimeoutInMilliseconds: ${REPLY_TIMEOUT_IN_MILLISECONDS}
  maxFailedEvents: ${MAX_FAILED_EVENTS:1}

logging:
  level:
    root: ${LOGGING_LEVEL:INFO}

management:
  endpoints:
    web:
      exposure:
        include: health,scheduledtasks,liquibase,metrics