name: A workflow to validate PRs

on:
  pull_request:
    branches: [ Bahmni-IPD-master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
      - name: Build & Test
        run: ./mvnw clean install